apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: {{ .Values.global.namespace }}
spec:
  hosts:
  - {{ printf "grafana.%s" .Values.global.domain | quote }}
  gateways:
  - cnvrg-gateway
  http:
  - route:
    - destination:
        host: {{ printf "grafana.%s.svc.cluster.local" .Values.global.namespace }}
