apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: domain-register
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domain-register
  template:
    metadata:
      labels:
        app: domain-register
    spec:
      containers:
      - args:
        - python run.py
        command:
        - /bin/sh
        - -c
        image: cnvrg/domain-register
        imagePullPolicy: Always
        name: domain
        env:
        - name: CNVRG_NAMESPACE
          value: {{ .Values.global.namespace }}
        - name: DOMAIN
          value:  {{ printf "*.%s" .Values.global.domain | quote }}
        - name: HOSTED_ZONE_ID
          value: {{ .Values.global.domain_hosted_zone_id }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.global.domain_access_key }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.global.domain_secret_key }}
      serviceAccount: cnvrg-cert-manager
      serviceAccountName: cnvrg-cert-manager
