kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cnvrg-app-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: cnvrg-app
  name: cnvrg-app
  namespace: {{ .Values.global.namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cnvrg-app-clusterrole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cnvrg-app-role
subjects:
- kind: ServiceAccount
  name: cnvrg-app
  namespace: {{ .Values.global.namespace }}
