apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: leah@cnvrg.io
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          region: us-east-2
          hostedZoneID: {{ .Values.global.domain_hosted_zone_id }}
          accessKeyID: {{ .Values.global.domain_access_key }}
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: prod-route53-credentials-secret
  namespace: {{ .Values.global.namespace }}
data:
  secret-access-key: {{ .Values.global.domain_secret_key | b64enc }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: domain-ingress-certs
  namespace: {{ .Values.global.namespace }}
spec:
  acme:
    config:
    - dns01:
        provider: aws-dns-prod
      domains:
      - {{ printf "*.%s" .Values.global.domain | quote }}
  dnsNames:
  - {{ printf "*.%s" .Values.global.domain | quote }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  renewBefore: 12h
  secretName: istio-ingressgateway-certs
